
services:
  node:
    image: testmongo202405-node:${version}
    container_name: node-${version}
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3089:3000"
  
  mongo:
    image: testmongo202405-mongo:${version}
    container_name: mongo-${version}
    build:
      context: .
      dockerfile: ./Dockerfile.mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
      MONGO_USERNAME: ${MONGODB_USER}
      MONGO_PASSWORD: ${MONGODB_PASS}
    restart: always
    volumes: 
      - D:/mongodblocal/data:/projectsDB/data
      - ./mongod.cfg:/etc/mongo/mongod.cfg
      - ./initDB.sh:/docker-entrypoint-initdb.d/init.sh
    command: 
      - '--auth'
      - '-f'
      - '/etc/mongo/mongod.cfg'
    ports:
      - 27017:27017
    

